// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARw1bgMtQad6mMbJ-lMLYoH3U2XcVFVrU',
    appId: '1:131227637794:web:1d75c6730283be8552527b',
    messagingSenderId: '131227637794',
    projectId: 'detect-it-new',
    authDomain: 'detect-it-new.firebaseapp.com',
    storageBucket: 'detect-it-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmVac2XJ0V9Q7Qfq-ZM40BtOSUpq4chXI',
    appId: '1:131227637794:android:2aac7aac592c269552527b',
    messagingSenderId: '131227637794',
    projectId: 'detect-it-new',
    storageBucket: 'detect-it-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8GZYMpthodfBZ-LZM1OaWzWki8lHsyDs',
    appId: '1:131227637794:ios:97100f24ab146a5852527b',
    messagingSenderId: '131227637794',
    projectId: 'detect-it-new',
    storageBucket: 'detect-it-new.firebasestorage.app',
    iosBundleId: 'com.example.detectIt',
  );
}
